name: "Prepare PR for UA Review"
description: "Github Action to prepare PR for UA Review when i18n.properties files are changed in a merged PR to main branch"

inputs:
  token:
    description: 'GitHub token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      id: checkout-code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Use Node.js 18.13.0
      uses: actions/setup-node@v4
      with:
        node-version: "18.13.0"

    - name: Get Diff
      id: get-env
      shell: bash
      run: |
        {
           echo 'DIFF<<EOF'
           git diff ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '**/i18n.properties'
           echo EOF
         } >> "$GITHUB_OUTPUT"

    - name: Display Diff
      run: |
        echo "${{env.DIFF}}"
      shell: bash
      env:
        DIFF: ${{ steps.get-env.outputs.DIFF }}

    - name: Check Condition
      id: check-condition
      shell: bash
      run: |
        if [ "$DIFF" == "" ]; then
          echo "exit_job=true" >> $GITHUB_OUTPUT
        else
          echo "exit_job=false" >> $GITHUB_OUTPUT
        fi
      env:
        DIFF: ${{ steps.get-env.outputs.DIFF }}

    - name: Exit Job if NO Diff
      if: ${{ steps.check-condition.outputs.exit_job == 'true' }}
      shell: bash
      run: |
        echo "Exiting job early because of no diff on i18n.properties files."
        exit 0

    - name: Apply Diff to EN #TODO take care of EN_US too
      if: ${{ steps.check-condition.outputs.exit_job != 'true' }}
      run: node ".${{ github.action_path }}/action.js"
      shell: bash
      env:
        DIFF: ${{ steps.get-env.outputs.DIFF }}
        ENUS: "true" #TODO service-cockpit-api true, service-eventlogs false

    - name: Debug Git State
      if: ${{ steps.check-condition.outputs.exit_job != 'true' }}
      shell: bash
      run: |
        git status
        git log -1
        git branch
        echo "${{ toJson(github.event) }}"

    - name: Create Pull Request
      if: ${{ steps.check-condition.outputs.exit_job != 'true' }}
      uses: peter-evans/create-pull-request@v5
      with:
        base: main #TODO master
        branch-suffix: random
        reviewers: ${{ github.event.pull_request.user.login }}
        # assignees: ${{ github.event.pull_request.user.login }} #TODO real assignee
        labels: "UA"
        draft: true
        title: "UA Review for Pull Request #${{ github.event.pull_request.number }}"
        body: |
          this is triggered automatically by below Pull Request for UA Review.
          Pull Request Title: ${{ github.event.pull_request.title }}
          Pull Request URL: ${{ github.event.pull_request.html_url }}
          Pull Request Body: ${{ github.event.pull_request.body }}
          Commit Id: ${{ github.event.pull_request.head.sha}}
          Auto-generated by [create-pull-request](https://github.com/peter-evans/create-pull-request)
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
